#!/bin/bash
set -eux # -x for verbose logging to juju debug-log

# Install the deps
juju-log "Installing system build dependencies."
apt-get -y install build-essential git

juju-log "Installing Bookie from Git."
git clone https://github.com/bookieio/Bookie.git Bookie
cd Bookie

juju-log "Installing Bookie dependencies."
NONINTERACTIVE=true make sysdeps

juju-log "Running make install, this will take a while."
make install
