#!/bin/bash
set -eux # -x for verbose logging to juju debug-log

# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

#!/bin/bash

# install the deps
juju-log "Installing system build dependencies."
apt-get -y install build-essential git

juju-log "Installing Bookie from Git."
git clone git://github.com/mitechie/Bookie.git
cd Bookie

juju-log "Installing Bookie dependencies."
NONINTERACTIVE=true make sysdeps

# this will take a while
juju-log "Running make install, this will take a while."
make install

juju-log "Opening ports needed, host:6543"
open-port 6543/tcp
