#!/bin/bash
set -eux # -x for verbose logging to juju debug-log

# install the deps
juju-log "Installing system build dependencies."
#apt-get -y install build-essential git
apt-get -y install build-essential git

juju-log "Installing Bookie from Git."

git clone `config-get branch`
cd Bookie

juju-log "Installing Bookie dependencies."
NONINTERACTIVE=true make sysdeps

# this will take a while
juju-log "Running make install, this will take a while."
make install

juju-log "Install uwsgi to run the app from."
bin/pip install uwsgi

juju-log "Opening ports needed, host:6543"
open-port 6543/tcp
